version: '3.8'

services:
  soundboard:
    image: soundboard:latest
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      PORT: 3000
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NEXT_PUBLIC_PRIMARY_COLOR: ${NEXT_PUBLIC_PRIMARY_COLOR:-hsl(222.2 47.4% 11.2%)}
      NEXT_PUBLIC_BACKGROUND_COLOR: ${NEXT_PUBLIC_BACKGROUND_COLOR:-hsl(0 0% 100%)}
      NEXT_PUBLIC_CARD_COLOR: ${NEXT_PUBLIC_CARD_COLOR:-hsl(240 5.9% 90%)}
      NEXT_PUBLIC_TEXT_COLOR: ${NEXT_PUBLIC_TEXT_COLOR:-hsl(222.2 84% 4.9%)}
    volumes:
      # Mount data directory which will contain sounds.yaml and other config
      - app_data:/app/data
      # Mount audio files directory for persistence
      - audio_files:/app/public/audio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  audio_files:
    driver: local
  app_data:
    driver: local